language: generic

sudo: required

services:
         - docker

before_install:

         - docker build -t mansoor9891/docker-react -f Dockerfile.dev .
         
script:

         
         - docker run -e CI=true mansoor9891/docker-react npm run test


