sudo: required

services:
         - docker

before_install:

         - docker build -t mansoor9891/docker-react -f Dockerfile.dev .
         
script:

         - docker run mansoor9891/docker-react npm run test -- --coverage


